# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PATH_TO_PROJECT: './myproject/src'
  MY_NAME: Lincoln
  VERSION: 5

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "hello_world"
  hello_world:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Access an environment variable from the workspace scope in this file
        run: echo "name $MY_NAME, path $PATH_TO_PROJECT"

      - name: Run only if version is OK and the previous step succeeded
        if: success() && env.VERSION > 4
        run: echo Version is OK

  # Add another job      
  run_script_file:
    name: Run a Python script that is in our repo
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PATH_TO_PROJECT }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      # can add in code to discover things about the environment you're running in
      - run: pwd
      - run: which python
      - run: which python3
      - run: pip install Pillow
      - run: python my_script.py 400 300 out.png
      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: placeholder_image
          path: ${{ env.PATH_TO_PROJECT }}/out.png