name: Use repository secrets

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  use_secrets:
    name: Access secrets in the repository
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Print out the password!
          run: echo Your password is ${{ secrets.password }}
    
        - name: Can we run a function on a secret?
          run: echo ${{ startsWith(secrets.password, 'Pa') }}

        - name: Can we use data in JSON format?
          run: |
            echo The population of Oregon is ${{ fromJSON(secrets.secret_config).population }}
            echo Config for ${{ fromJSON(secrets.secret_config).city }}
            

